# Generated by Django 6.1 on 2026-08-26 11:29

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.projects.models.gen_public_id, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(max_length=500)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('crawling', 'crawling'), ('generating', 'generating'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=16)),
                ('status_message', models.CharField(blank=True, default='', max_length=255)),
                ('progress', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.domaintype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=16)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='TenantOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to='projects.project')),
            ],
        ),
    ]
