# Generated by Django 6.1 on 2026-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='menus_edited',
            field=models.BooleanField(default=False),
        ),
    ]
