# Generated by Django 6.1 on 2026-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_menus_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.CharField(blank=True, default='blue_sky', max_length=32),
        ),
    ]
