# Generated by Django 6.1 on 2026-08-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
