# Generated by Django 6.1 on 2026-08-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='project',
            name='gemini_model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='openrouter_api_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='project',
            name='openrouter_fallback_model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='project',
            name='openrouter_model',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
