# Generated by Django 6.1 on 2026-08-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_gemini_api_key_project_gemini_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='openrouter_api_key',
        ),
        migrations.RemoveField(
            model_name='project',
            name='openrouter_fallback_model',
        ),
        migrations.RemoveField(
            model_name='project',
            name='openrouter_model',
        ),
    ]
