# Generated by Django 6.1 on 2026-08-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_openrouter_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lang',
            field=models.CharField(blank=True, db_index=True, default='ko', max_length=8),
        ),
    ]
