# Generated by Django 6.1 on 2026-08-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_theme'),
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(blank=True, default='', max_length=32)),
                ('origin', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_detail', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('new', 'new'), ('read', 'read'), ('resolved', 'resolved')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
