<script setup lang="ts">
// 영어 사일로용 — 이용약관 / AI 이용고지 / 개인정보처리방침 / 프로그램 사용동의
</script>

<template>
  <section class="terms-section">
    <div class="terms-title">
      <h2>Terms &amp; Policies</h2>
      <p class="note">Terms of use and procedures for the WebMCP AI Assistant service, and the rights and obligations of users and the service provider.</p>
    </div>

    <details class="terms-accordion">
      <summary>📋 Terms of Service</summary>
      <div class="terms-body">
        <h4>Chapter 1. General Provisions</h4>
        <h4>Article 1 (Purpose)</h4>
        <p>These Terms specify the conditions and procedures for using all services provided by the WebMCP AI Assistant service (the "Service"), and the rights, obligations and responsibilities of users and the service provider.</p>
        <h4>Article 2 (Definitions)</h4>
        <p>The terms used in these Terms are defined as follows.</p>
        <ul>
          <li><b>Service</b> : The AI-based website consultation widget and related functions provided by the WebMCP AI Assistant</li>
          <li><b>User (Member)</b> : An individual or business that agrees to these Terms and is granted the right to register a project and use the Service</li>
          <li><b>Project</b> : An AI assistant generation unit that includes the website URL, domain type, theme, etc. registered by the user</li>
          <li><b>AI Assistant (Widget)</b> : An AI chatbot installed on the user's website that converses with visitors</li>
        </ul>
        <h4>Article 3 (Effect and Changes of the Terms)</h4>
        <ul>
          <li>These Terms are posted on the service screen and take effect when the user registers a project.</li>
          <li>If the service provider changes these Terms, the changes will be announced at least 7 days before the effective date, and take effect at the time of announcement.</li>
          <li>If the user does not express intent to reject despite clear notice, the user is deemed to have accepted the amended Terms.</li>
          <li>Users who do not accept the amended Terms may stop using the Service and delete their projects.</li>
        </ul>
        <h4>Article 4 (Matters Not Specified)</h4>
        <p>Matters not specified in these Terms follow applicable laws and, absent such provisions, general practices.</p>

        <h4>Chapter 2. Use of the Service</h4>
        <h4>Article 5 (Formation of Registration)</h4>
        <ul>
          <li>Registration is completed when the applicant records the required information (website URL, name, etc.) in the online registration form.</li>
          <li>The service provider mayreject or delete registrations that fall under the following.
            <ul>
              <li>Application under another person's name</li>
              <li>False information in the registration</li>
              <li>Applications intended to harm public order or morals</li>
              <li>Interfering with other users' service or misusing information</li>
              <li>Acts prohibited by law or these Terms</li>
              <li>Other cases where registration requirements are insufficient</li>
            </ul>
          </li>
        </ul>
        <h4>Article 6 (Service Content and Use)</h4>
        <ul>
          <li>When a website URL is registered, the Service crawls the site and automatically generates an AI assistant widget.</li>
          <li>Users can change the domain type and widget theme, and edit quick menu questions <b>once</b>.</li>
          <li>Up to <b>5</b> projects can be created per account.</li>
          <li>The generated AI assistant widget can only be installed on the website registered by the user.</li>
        </ul>
        <h4>Article 7 (Limitations of AI Answers)</h4>
        <ul>
          <li>AI assistant answers are generated by a large language model (LLM) and <b>may be inaccurate</b>. They should not be considered medical, legal, or financial advice.</li>
          <li>Important decisions (treatment, legal, investment, etc.) should always be made after consulting a professional.</li>
          <li>AI answers are based on collected website information; information not on the website may be inaccurate.</li>
          <li>The service provider does not guarantee the accuracy, completeness, or quality of AI-generated answers.</li>
        </ul>
        <h4>Article 8 (Service Hours and Suspension)</h4>
        <ul>
          <li>The Service is available 24/7 year-round unless there are business or technical reasons, such as scheduled maintenance.</li>
          <li>The service provider is not responsible for service interruption or data loss due to national emergencies, power outages, facility failures, or force majeure.</li>
          <li>The service provider may temporarily modify, change, or suspend the Service without liability to users or third parties.</li>
          <li>If a user violates these Terms, the service provider may restrict or suspend the user's service and block access.</li>
        </ul>

        <h4>Chapter 3. Obligations and Responsibilities</h4>
        <h4>Article 9 (Service Provider's Obligations)</h4>
        <ul>
          <li>The service provider does not engage in acts prohibited by law or these Terms, and strives to provide the Service continuously and stably.</li>
          <li>The service provider performs notices and announcements about changes diligently through the prescribed procedures.</li>
          <li>If the service provider determines that a user has violated these Terms, it may delete related information without consent.</li>
        </ul>
        <h4>Article 10 (User Obligations and Service Restrictions)</h4>
        <ul>
          <li>If information provided by the user is found or reasonably suspected to be false, the service provider may suspend all or part of the service and is not liable for resulting disadvantages.</li>
          <li>The user bears all responsibility for all forms of information posted, transmitted, or obtained through the Service.</li>
          <li>Users must not engage in the following through the Service.
            <ul>
              <li>Using another person's ID or credentials</li>
              <li>Transmitting vulgar, obscene, insulting, threatening content or content that infringes others' privacy</li>
              <li>Falsifying the source of transmitted content</li>
              <li>Posting or transmitting content prohibited by law or these Terms</li>
              <li>Infringing others' patents, trademarks, trade secrets, copyrights, or other intellectual property</li>
              <li>Sending unsolicited ads, promotional materials, spam, etc. without approval</li>
              <li>Collecting or storing other users' personal information</li>
            </ul>
          </li>
          <li>Users may not conduct any commercial activities through the Service without prior consent.</li>
          <li>Users may not copy, reproduce, modify, translate, publish, broadcast, or otherwise use information obtained through the Service, or provide it to others, without prior consent.</li>
        </ul>
        <h4>Article 11 (Prohibited Acts Including Automated Tools)</h4>
        <ul>
          <li>Using automated tools (macros, scraping, etc.) without permission to bypass or disable Service functions</li>
          <li>Accessing the Service with continuously changing IPs or circumventing access restrictions</li>
          <li>Any act that interferes with or may interfere with stable Service operation</li>
          <li>Illegal acts such as personal information misuse/leakage, service delays or interruptions may result in legal penalties and liability.</li>
        </ul>
        <h4>Article 12 (Intellectual Property)</h4>
        <ul>
          <li>Intellectual property and other rights related to software, images, logos, designs, service names, and trademarks provided through the Service belong to the service provider.</li>
          <li>Users may not reproduce, modify, distribute, sell, or transfer them, or provide them to third parties without explicit approval.</li>
        </ul>
        <h4>Article 13 (No Transfer)</h4>
        <p>Users may not transfer or gift their service rights or registration status to others, or provide them as collateral.</p>
        <h4>Article 14 (Damages and Disclaimer)</h4>
        <ul>
          <li>Except for intentional crimes, the service provider is not liable for damages arising from the free Service.</li>
          <li>The service provider has no obligation to guarantee any opinions or information expressed in the Service and is not liable for benefits gained or losses incurred from relying on the information.</li>
          <li>The service provider is not responsible for transactions or disputes between users or between users and third parties mediated by the Service.</li>
          <li>The Service may be suspended due to natural disasters, system maintenance, or other force majeure.</li>
        </ul>
        <h4>Article 15 (Governing Law and Jurisdiction)</h4>
        <p>Disputes between the service provider and users regarding the use of the Service are governed by the laws of the Republic of Korea, and lawsuits are filed with the courts of Korea.</p>
      </div>
    </details>

    <details class="terms-accordion">
      <summary>🤖 AI Disclosure</summary>
      <div class="terms-body">
        <h4>Prior Notice and Output Labeling under the AI Basic Act</h4>
        <p>Article 31 of the AI Basic Act divides transparency obligations for generative AI into two stages.</p>
        <p>First, AI businesses providing products or services based on generative AI must <b>notify users in advance</b> that the product or service operates on generative AI.</p>
        <p>Separately, outputs created by generative AI or services using it must be <b>labeled</b> as AI-generated.</p>
        <p>In particular, voices, images, and videos that are difficult to distinguish from reality must be notified or labeled in a way that users can clearly recognize them as AI-generated.</p>
        <p>This Service discloses that some or all of this work (or articles/posts) was created using artificial intelligence (AI) technology for data collection and drafting, or with editing assistance. We have used the technology legitimately without infringing others' copyrights and faithfully fulfill this disclosure obligation.</p>

        <h4>AI Models Used by This Service</h4>
        <ul>
          <li>This Service (WebMCP AI Assistant) is an AI-based consultation widget using <b>Google Gemini</b> and <b>OpenAI OSS-120B</b> for answer generation.</li>
          <li><b>Google Gemini</b> is used for real-time chat and site summaries, and <b>OpenAI OSS-120B</b> for Q&amp;A batch generation.</li>
          <li>All answers generated by the AI assistant are <b>AI-generated outputs</b>. Please use them with this in mind.</li>
        </ul>

        <h4>AI Usage Precautions</h4>
        <ul>
          <li>AI assistant answers are generated by a large language model (LLM) and <b>may be inaccurate</b>. They should not be considered medical, legal, or financial advice.</li>
          <li>For important decisions (treatment, legal, investment, etc.), please consult a professional.</li>
          <li>AI answers are based on collected website information; information not on the website may be inaccurate.</li>
          <li>The service provider is not liable for damages caused by AI-generated answers.</li>
          <li>AI answer quality may vary with usage and model status; the Service does not guarantee it.</li>
          <li>AI-generated outputs may be difficult to distinguish from reality, so please verify important information from the original source.</li>
        </ul>
      </div>
    </details>

    <details class="terms-accordion">
      <summary>🔒 Privacy Policy</summary>
      <div class="terms-body">
        <h4>1. Purpose of Processing Personal Information</h4>
        <p>The WebMCP AI Assistant service (the "Service") processes personal information for the following purposes and does not use it for any other purposes.</p>
        <ul>
          <li>Confirming membership registration, identifying/authenticating users for service provision, maintaining/managing membership</li>
          <li>Creating and operating AI assistant widgets, handling customer inquiries and consultations</li>
          <li>Improving service quality and analyzing usage statistics</li>
        </ul>

        <h4>2. Processing and Retention Period</h4>
        <p>① The Service processes and retains personal information within the retention period consented to by the data subject or required by law.</p>
        <p>② Specific retention periods are as follows.</p>
        <ul>
          <li>Membership registration and management: member information such as email and name</li>
          <li>Retention period: deleted immediately upon membership withdrawal</li>
          <li>Customer inquiries: retained for 2 years after receipt (unless otherwise required by law)</li>
        </ul>

        <h4>3. Rights and Obligations of Data Subjects and Legal Representatives</h4>
        <p>Users may exercise the following rights as personal information subjects.</p>
        <ul>
          <li>Request to access personal information</li>
          <li>Request correction of errors</li>
          <li>Request deletion</li>
          <li>Request suspension of processing</li>
        </ul>

        <h4>4. Personal Information Items Processed</h4>
        <p>The Service processes the following personal information items.</p>
        <ul>
          <li><b>At membership registration</b> : email, name (purpose: membership management and service provision; retained until withdrawal or consent withdrawal)</li>
          <li><b>At customer inquiries</b> : name, email, inquiry content (purpose: replies to inquiries and consultations; retained for 2 years after receipt)</li>
          <li><b>When using AI chat</b> : chat question content (purpose: AI answer generation and service quality improvement; discarded when the purpose is achieved)</li>
        </ul>
        <p>To protect children's personal information, membership registration is limited to those aged 14 or older; the Service does not collect children's personal information.</p>

        <h4>5. Destruction of Personal Information</h4>
        <p>The Service destroys personal information without delay once the processing purpose is achieved.</p>
        <ul>
          <li><b>Destruction procedure</b> : Information entered by users is moved to a separate DB and stored for a certain period according to internal policy and applicable laws, then destroyed. Information moved to the DB is not used for other purposes except as required by law.</li>
          <li><b>Destruction deadline</b> : Personal information is destroyed within 5 days after the retention period expires, or within 5 days from the day it becomes unnecessary (purpose achieved, service discontinued, business ended, etc.).</li>
        </ul>

        <h4>6. Installation/Operation of Automatic Collection Devices and Refusal</h4>
        <p>① The Service uses 'cookies' to store and frequently retrieve usage information to provide individualized services.</p>
        <p>② Cookies are small amounts of information sent by the operating server to the user's browser, sometimes stored on the user's PC hard disk.</p>
        <ul>
          <li>a. Purpose of cookies: to analyze visits and usage patterns of each service and website, and to provide optimized information including secure connections.</li>
          <li>b. Installation/operation and refusal: users can refuse cookie storage via the browser settings (Tools &gt; Internet Options &gt; Privacy).</li>
          <li>c. Refusing cookies may make personalized services difficult to use.</li>
        </ul>

        <h4>7. Personal Information Protection Officer</h4>
        <p>① The Service designates the following personal information protection officer to oversee personal information processing and handle complaints and remedies.</p>
        <ul>
          <li><b>Personal Information Protection Officer</b> : Jangwon Lee / Title: Managing Director / Tel: 02-752-0719</li>
        </ul>
        <p>② Inquiries, complaints, and remedies related to personal information protection can be directed to the protection officer, who will respond and process them without delay.</p>

        <h4>8. Changes to the Privacy Policy</h4>
        <p>This policy takes effect upon implementation. If changes are added, deleted, or amended according to laws and policies, they will be announced via notices at least 7 days before implementation.</p>

        <h4>9. Measures for Security</h4>
        <p>According to Article 29 of the Personal Information Protection Act, the Service implements the following technical, administrative, and physical measures.</p>
        <ul>
          <li><b>Minimizing and training staff handling personal information</b> : Dedicated employees are assigned and access is limited to minimize handlers.</li>
          <li><b>Technical measures against hacking</b> : Security programs are installed and periodically updated to prevent leakage and damage from hacking or viruses; systems are located in controlled areas with technical and physical monitoring.</li>
          <li><b>Encryption</b> : Personal information such as passwords is encrypted and stored; important data uses file and transmission encryption or file locking.</li>
          <li><b>Access log retention and anti-tampering</b> : Access records are retained for at least 6 months with security functions to prevent tampering, theft, or loss.</li>
          <li><b>Access restriction</b> : Access to the personal information database is controlled through granting, changing, and revoking access rights, and an intrusion prevention system blocks unauthorized external access.</li>
        </ul>

        <h4>10. Remedies for Rights Infringement</h4>
        <p>The following organizations are separate from the service provider. If you are not satisfied with our personal information complaint handling or need further assistance, please contact them.</p>
        <ul>
          <li><b>Personal Information Infringement Report Center</b> (operated by KISA) : privacy.kisa.or.kr / 118 (no area code)</li>
          <li><b>Personal Information Dispute Mediation Committee</b> : www.kopico.go.kr / 1833-6972 (no area code)</li>
          <li><b>Supreme Prosecutors' Office Cyber Crime Unit</b> : 02-3480-3573 (www.spo.go.kr)</li>
          <li><b>National Police Agency Cyber Safety Bureau</b> : 182 (http://cyberbureau.police.go.kr)</li>
        </ul>
      </div>
    </details>

    <details class="terms-accordion">
      <summary>✅ Program Use Agreement</summary>
      <div class="terms-body">
        <ul>
          <li>By using this Service (WebMCP AI Assistant), you are deemed to have agreed to the following.</li>
          <li>Members must not use the Service's widget for illegal or inappropriate purposes.</li>
          <li>Members may not copy, distribute, or modify the Service's source code or content without authorization.</li>
          <li>Members are responsible for answers generated through the AI assistant and must not abuse them.</li>
          <li>The Service may be suspended due to natural disasters, system maintenance, or other force majeure.</li>
          <li>These terms may change with prior notice following service policy changes.</li>
        </ul>
      </div>
    </details>
  </section>
</template>