# Generated by Django 6.1 on 2026-08-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_allowed_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='billing_address',
            field=models.TextField(blank=True, default='', verbose_name='결제 주소'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_company',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='회사명'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_contact',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='결제 담당자'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='결제 이메일'),
        ),
        migrations.AddField(
            model_name='user',
            name='billing_note',
            field=models.TextField(blank=True, default='', verbose_name='결제 비고'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_currency',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='통화'),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True, verbose_name='월 결제 금액'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='대표 전화번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='보조 전화번호'),
        ),
    ]
