# Generated by Django 5.2.17 on 2026-09-07 20:35

from django.db import migrations, models


def seed_default_code(apps, schema_editor):
    """기본 가입 코드 OneAir1234 시드 — 양쪽 사일로(ko/en) 모두 허용."""
    SignupCode = apps.get_model('accounts', 'SignupCode')
    if not SignupCode.objects.filter(code='OneAir1234').exists():
        SignupCode.objects.create(code='OneAir1234', lang='', note='기본 가입 코드')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_billing_address_user_billing_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='가입 코드')),
                ('lang', models.CharField(blank=True, default='', max_length=2, verbose_name='사일로 제한')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='최대 사용 횟수')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='사용 횟수')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 시각')),
                ('note', models.CharField(blank=True, default='', max_length=128, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_default_code, migrations.RunPython.noop),
    ]
