import json
import mimetypes
from pathlib import Path

from django.conf import settings
from django.http import Http404, HttpResponse
from django.views.decorators.clickjacking import xframe_options_exempt
from rest_framework.decorators import api_view, permission_classes
from rest_framework.exceptions import ValidationError
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from apps.projects.models import Project
from core.minify import minify_js

from .models import Widget


def _owned_project(request, pk) -> Project:
    p = Project.objects.filter(pk=pk).first()
    if p is None:
        raise ValidationError('프로젝트 없음')
    if p.user_id != request.user.id and request.user.role != 'admin':
        raise ValidationError('권한 없음')
    return p


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def qna(request, pk):
    from apps.pipeline.models import GeneratedQnA
    rows = GeneratedQnA.objects.filter(project=_owned_project(request, pk))
    return Response([
        {'menuLabel': r.menu_label, 'question': r.question, 'answerMd': r.answer_md}
        for r in rows
    ])


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def widget_config(request, pk):
    w = Widget.current(_owned_project(request, pk))
    if w is None:
        raise ValidationError('아직 생성된 위젯이 없습니다.')
    return Response({'config': w.public_config()})   # system_prompt 미포함


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def download_config_js(request, pk):
    w = Widget.current(_owned_project(request, pk))
    if w is None:
        raise ValidationError('위젯 없음')
    js = f'// Auto-generated by WebMCP Auto\nwindow.WebMCPConfig = {w.config_json};\n'
    resp = HttpResponse(js, content_type='application/javascript')
    resp['Content-Disposition'] = 'attachment; filename="webmcp-config.js"'
    from apps.projects.models import DownloadLog
    DownloadLog.objects.create(project_id=pk, user=request.user, file_type='config_js')
    return resp


@api_view(['GET'])
@permission_classes([IsAuthenticated])
def download_bundle(request, pk):
    """자체 호스팅 번들 zip."""
    import io
    import zipfile
    from pathlib import Path

    project = _owned_project(request, pk)
    w = Widget.current(project)
    if w is None:
        raise ValidationError('위젯 없음')

    dist_dir = Path(settings.BASE_DIR).parent / 'widget-dist'
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, 'w') as zf:
        zf.writestr('webmcp-config.js', f'window.WebMCPConfig = {w.config_json};\n')
        # JS 파일은 난독화+최적화, CSS 는 그대로 (스타일시트는 난독화 불가)
        for name in ['webmcp.js', 'widget.js', 'webmcp-widget.js']:
            f = dist_dir / name
            if f.exists():
                zf.writestr(name, minify_js(f.read_text()))
        css = dist_dir / 'widget.css'
        if css.exists():
            zf.writestr('widget.css', css.read_text())
        zf.writestr('INSTALL.md', _install_md(project))
    resp = HttpResponse(buf.getvalue(), content_type='application/zip')
    resp['Content-Disposition'] = f'attachment; filename="webmcp-bundle-{project.public_id}.zip"'
    from apps.projects.models import DownloadLog
    DownloadLog.objects.create(project=project, user=request.user, file_type='bundle_zip')
    return resp


def _install_md(project) -> str:
    return (
        f'# {project.name} AI 위젯 설치 가이드\n\n'
        f'이 번들에는 아래 5개 파일이 포함되어 있습니다.\n\n'
        f'| 파일 | 역할 |\n'
        f'|------|------|\n'
        f'| `webmcp-config.js` | 위젯 설정(색상·메뉴·질문·API 주소) — 수정 가능 |\n'
        f'| `webmcp.js` | 위젯 로더/초기화 스크립트 (난독화됨) |\n'
        f'| `webmcp-widget.js` | 위젯 핵심 동작 스크립트 (난독화됨) |\n'
        f'| `widget.js` | 위젯 실행 스크립트 (난독화됨) |\n'
        f'| `widget.css` | 위젯 스타일시트 |\n\n'
        f'> 🔒 `webmcp.js`·`widget.js`·`webmcp-widget.js` 는 난독화·최적화되어 제공됩니다. '
        f'`webmcp-config.js`(설정)와 `widget.css`(스타일)는 수정 가능합니다.\n\n'
        f'---\n\n'
        f'## 1단계: 파일 업로드 (호스팅 서버)\n\n'
        f'1. `webmcp-bundle-{project.public_id}.zip` 압축을 해제합니다.\n'
        f'2. FTP/SFTP 또는 호스팅 파일 관리자로 홈페이지 루트(예: `public_html`, `www`, `html`)에 '
        f'**5개 파일을 모두 업로드**합니다.\n'
        f'   - 파일 경로 예시: `https://www.example.com/webmcp-config.js`\n'
        f'3. 업로드 후 브라우저 주소창에 `https://www.example.com/webmcp-config.js`를 입력해 '
        f'파일이 정상 접근되는지 확인합니다. (설정 내용이 보이면 성공)\n\n'
        f'---\n\n'
        f'## 2단계: HTML 편집 (위젯 삽입)\n\n'
        f'위젯을 표시할 페이지의 HTML을 편집합니다.\n\n'
        f'1. 홈페이지 관리자 도구 또는 HTML 에디터(예: 드림위버, VS Code, 호스팅 제공 편집기)로 '
        f'**해당 페이지의 HTML 소스**를 엽니다.\n'
        f'2. `</body>` 태그 **직전**에 아래 코드를 붙여넣습니다.\n\n'
        f'```html\n'
        f'<!-- WebMCP AI 위젯 -->\n'
        f'<script src="webmcp-config.js"></script>\n'
        f'<script src="webmcp.js"></script>\n'
        f'<link rel="stylesheet" href="widget.css" />\n'
        f'<script src="widget.js"></script>\n'
        f'```\n\n'
        f'3. 파일을 저장하고 페이지를 새로고침합니다.\n'
        f'4. 페이지 **우측 하단**에 AI 상담 버튼이 나타나면 설치 성공입니다.\n\n'
        f'> 💡 파일을 루트가 아닌 하위 폴더(예: `/widget/`)에 업로드했다면, '
        f'`src` 경로를 `widget/webmcp-config.js`처럼 해당 경로로 수정하세요.\n\n'
        f'---\n\n'
        f'## 사용 방법\n\n'
        f'- 페이지 우측 하단의 **AI 상담 버튼**을 클릭하면 채팅창이 열립니다.\n'
        f'- 빠른메뉴 질문을 누르거나 직접 질문을 입력하면, 수집된 사이트 정보를 바탕으로 AI가 답변합니다.\n'
    )


# ── 데이터 플레인 ────────────────────────────────────────────

def health(request):
    return HttpResponse('{"status":"ok"}', content_type='application/json')


def ready(request):
    from django.conf import settings as s
    ok = bool(getattr(s, 'GEMINI_API_KEY', ''))
    return HttpResponse(
        json.dumps({'ready': ok, 'geminiKey': ok}),
        content_type='application/json', status=200 if ok else 503,
    )


def embed_js(request, public_id):
    """호스팅 로더 — config 주입 후 위젯 로드."""
    project = Project.objects.filter(public_id=public_id).first()
    if project is None:
        return HttpResponse('// unknown widget\n', status=404, content_type='application/javascript')
    w = Widget.current(project)
    if w is None:
        return HttpResponse('// not ready\n', status=404, content_type='application/javascript')
    base = settings.SAAS_PUBLIC_URL.rstrip('/')
    js = (
        f'(function(){{\n'
        f'  window.WebMCPConfig = {w.config_json};\n'
        f'  var s = document.createElement("script"); s.src = "{base}/widget-dist/webmcp.js"; s.async = false;\n'
        f'  document.head.appendChild(s);\n'
        f'  var l = document.createElement("link"); l.rel = "stylesheet"; l.href = "{base}/widget-dist/widget.css";\n'
        f'  document.head.appendChild(l);\n'
        f'  var t = document.createElement("script"); t.src = "{base}/widget-dist/widget.js"; t.async = false;\n'
        f'  document.body.appendChild(t);\n'
        f'}})();\n'
    )
    return HttpResponse(js, content_type='application/javascript')


def widget_asset(request, path):
    """widget-dist 정적 파일 서빙."""
    dist_dir = Path(settings.BASE_DIR).parent / 'widget-dist'
    target = (dist_dir / path).resolve()
    if not str(target).startswith(str(dist_dir.resolve())) or not target.is_file():
        raise Http404('Asset not found')
    content_type, _ = mimetypes.guess_type(str(target))
    return HttpResponse(target.read_bytes(), content_type=content_type or 'application/octet-stream')


@xframe_options_exempt
def preview_html(request, pk):
    """동일 오리진 데모 HTML — iframe 내 렌더링을 위해 xframe_options_exempt 적용.

    사일로 언어(프로젝트 lang)에 따라 안내 문구를 한국어/영어로 표시한다.
    모바일에서는 위젯 런처(AI 버튼)가 하단에 고정되므로, 화면 하단 콘텐츠와 겹치지
    않게 safe-area + 하단 여백을 확보한다 (스마트폰에서 런처가 가려지는 문제 대응).
    """
    if not request.user.is_authenticated:
        return HttpResponse('login required', status=401)
    project = Project.objects.filter(pk=pk).first()
    if project is None or (project.user_id != request.user.id and request.user.role != 'admin'):
        return HttpResponse('forbidden', status=403)
    w = Widget.current(project)
    config = w.config_json if w else '{}'
    base = '/widget-dist/'
    lang = (getattr(project, 'lang', '') or 'ko').lower()
    if lang == 'en':
        html_title = f'{project.name} Demo'
        hint = 'Check the AI assistant with the 💬 button at the bottom-right.'
        badge = 'Preview'
    else:
        html_title = f'{project.name} 데모'
        hint = '우하단 💬 버튼으로 AI 비서를 확인하세요.'
        badge = '미리보기'
    html = f"""<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
<title>{html_title}</title>
<style>body{{font-family:sans-serif;margin:0;padding:48px;background:#fafafa}}
.hero{{max-width:720px;margin:0 auto}}h1{{color:#0e7490;margin:0 0 8px}}
.preview-badge{{display:inline-block;padding:3px 10px;border-radius:999px;background:#e0f2fe;color:#0c4a6e;font-size:12px;margin-bottom:10px}}
.hint{{color:#6b7280;font-size:14px;line-height:1.6}}
p.hint-card{{margin-top:28px;padding:12px 16px;background:#fff;border:1px solid #e5e7eb;border-radius:10px}}
/* 모바일: 위젯 런처(우하단 AI 버튼)와 콘텐츠가 겹치지 않게 하단 여백 확보.
   safe-area-inset-bottom 까지 더해 iOS 홈 인디케이터/주소창에도 가려지지 않는다. */
@media (max-width: 768px){{
  body{{padding:24px 20px calc(120px + env(safe-area-inset-bottom, 0px))}}
}}
</style>
<script>window.WebMCPConfig = {config};</script>
<script src="{base}webmcp.js"></script>
<link rel="stylesheet" href="{base}widget.css"/>
<script src="{base}widget.js"></script>
</head><body><div class="hero">
<span class="preview-badge">{badge}</span>
<h1>{project.name}</h1>
<p class="hint">{hint}</p>
</div></body></html>"""
    return HttpResponse(html)
