# Generated by Django 6.1 on 2026-08-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(default='🏢', max_length=8)),
                ('sort_order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='QuickMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('question', models.CharField(max_length=255)),
                ('prompt_hint', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('domain_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='catalogs.domaintype')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
