# Generated by Django 6.1 on 2026-08-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintype',
            name='category',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
