# Generated by Django 6.1 on 2026-08-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_domaintype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickmenu',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
