# Generated by Django 6.1 on 2026-08-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_quickmenu_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickmenu',
            name='answer_md',
            field=models.TextField(blank=True, default=''),
        ),
    ]
