# Generated by Django 6.1 on 2026-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_quickmenu_answer_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='domaintype',
            name='lang',
            field=models.CharField(blank=True, db_index=True, default='ko', max_length=8),
        ),
        migrations.AlterField(
            model_name='domaintype',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='domaintype',
            constraint=models.UniqueConstraint(fields=('code', 'lang'), name='uniq_domaintype_code_lang'),
        ),
    ]
