# Generated by Django 6.1 on 2026-08-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinejob',
            name='selected_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='source_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
