# Generated by Django 6.1 on 2026-08-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_pipelinejob_selected_urls_sitecontent_source_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='failed_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
